name: Deploy Laravel to ECS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495930421214:role/Laravel-demo-github-action-role
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t laravel-app:latest .
          docker tag laravel-app:latest 495930421214.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-demo:latest

      - name: Push to ECR
        run: docker push 495930421214.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-demo:latest
        
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: laravel-task-v2-revision.json
          service: laravel-task-service-6688
          cluster: laravel-cluster-demo
          image: 495930421214.dkr.ecr.ap-northeast-1.amazonaws.com/laravel-demo:latest

      - name: Notify success
        if: success()
        run: aws sns publish --topic-arn arn:aws:sns:ap-northeast-1:495930421214:sns-alert-demo --message "✅ ECS 部署成功" --subject "ECS 部署成功"

      - name: Notify failure
        if: failure()
        run: aws sns publish --topic-arn arn:aws:sns:ap-northeast-1:495930421214:sns-alert-demo --message "❌ ECS 部署失败" --subject "ECS 部署失败"
